# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'OfficeHelper.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(611, 533)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(-50, -70, 651, 561))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.tabWidget = QtWidgets.QTabWidget(self.groupBox)
        self.tabWidget.setGeometry(QtCore.QRect(50, 70, 611, 491))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.tabWidget_2 = QtWidgets.QTabWidget(self.tab)
        self.tabWidget_2.setGeometry(QtCore.QRect(0, 0, 891, 461))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget_2.sizePolicy().hasHeightForWidth())
        self.tabWidget_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setKerning(True)
        self.tabWidget_2.setFont(font)
        self.tabWidget_2.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setAutoFillBackground(False)
        self.tab_4.setObjectName("tab_4")
        self.gridLayoutWidget = QtWidgets.QWidget(self.tab_4)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 10, 576, 141))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.regexInput = QtWidgets.QTextEdit(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.regexInput.sizePolicy().hasHeightForWidth())
        self.regexInput.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(True)
        self.regexInput.setFont(font)
        self.regexInput.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.regexInput.setObjectName("regexInput")
        self.gridLayout.addWidget(self.regexInput, 0, 1, 1, 2)
        self.directoryButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.directoryButton.setObjectName("directoryButton")
        self.gridLayout.addWidget(self.directoryButton, 2, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(12)
        font.setKerning(True)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 4, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(12)
        font.setKerning(True)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(12)
        font.setKerning(True)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.fileButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.fileButton.setObjectName("fileButton")
        self.gridLayout.addWidget(self.fileButton, 2, 1, 1, 1)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.pdfCheck = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.pdfCheck.setObjectName("pdfCheck")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.pdfCheck)
        self.docxCheck = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.docxCheck.setObjectName("docxCheck")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.docxCheck)
        self.txtCheck = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.txtCheck.setObjectName("txtCheck")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.txtCheck)
        self.docCheck = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.docCheck.setObjectName("docCheck")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.docCheck)
        self.gridLayout.addLayout(self.formLayout, 4, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.tab_4)
        self.label_4.setGeometry(QtCore.QRect(10, 220, 581, 41))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(13)
        font.setUnderline(True)
        font.setKerning(True)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.regexTable = QtWidgets.QTableWidget(self.tab_4)
        self.regexTable.setGeometry(QtCore.QRect(10, 270, 581, 151))
        self.regexTable.setObjectName("regexTable")
        self.regexTable.setColumnCount(3)
        self.regexTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.regexTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.regexTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.regexTable.setHorizontalHeaderItem(2, item)
        self.searchButton = QtWidgets.QPushButton(self.tab_4)
        self.searchButton.setGeometry(QtCore.QRect(170, 160, 161, 51))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(12)
        font.setKerning(True)
        self.searchButton.setFont(font)
        self.searchButton.setObjectName("searchButton")
        self.regexExportButton = QtWidgets.QPushButton(self.tab_4)
        self.regexExportButton.setGeometry(QtCore.QRect(340, 170, 121, 31))
        self.regexExportButton.setObjectName("regexExportButton")
        self.tabWidget_2.addTab(self.tab_4, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.tab_5)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(0, 10, 591, 210))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_6 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(12)
        font.setKerning(True)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 3, 0, 1, 1)
        self.cleanupDirectoryButton = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.cleanupDirectoryButton.setObjectName("cleanupDirectoryButton")
        self.gridLayout_2.addWidget(self.cleanupDirectoryButton, 1, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(12)
        font.setKerning(True)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 1, 0, 1, 1)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.checkBox = QtWidgets.QCheckBox(self.gridLayoutWidget_2)
        self.checkBox.setObjectName("checkBox")
        self.gridLayout_4.addWidget(self.checkBox, 0, 0, 1, 1)
        self.checkBox_3 = QtWidgets.QCheckBox(self.gridLayoutWidget_2)
        self.checkBox_3.setObjectName("checkBox_3")
        self.gridLayout_4.addWidget(self.checkBox_3, 1, 0, 1, 1)
        self.checkBox_2 = QtWidgets.QCheckBox(self.gridLayoutWidget_2)
        self.checkBox_2.setObjectName("checkBox_2")
        self.gridLayout_4.addWidget(self.checkBox_2, 2, 0, 1, 1)
        self.checkBox_4 = QtWidgets.QCheckBox(self.gridLayoutWidget_2)
        self.checkBox_4.setObjectName("checkBox_4")
        self.gridLayout_4.addWidget(self.checkBox_4, 1, 1, 1, 1)
        self.checkBox_5 = QtWidgets.QCheckBox(self.gridLayoutWidget_2)
        self.checkBox_5.setObjectName("checkBox_5")
        self.gridLayout_4.addWidget(self.checkBox_5, 0, 1, 1, 1)
        self.checkBox_6 = QtWidgets.QCheckBox(self.gridLayoutWidget_2)
        self.checkBox_6.setObjectName("checkBox_6")
        self.gridLayout_4.addWidget(self.checkBox_6, 2, 1, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout_4, 3, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 4, 0, 1, 1)
        self.textEdit = QtWidgets.QTextEdit(self.gridLayoutWidget_2)
        self.textEdit.setObjectName("textEdit")
        self.gridLayout_2.addWidget(self.textEdit, 4, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.tab_5)
        self.label_8.setGeometry(QtCore.QRect(20, 270, 581, 41))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(13)
        font.setUnderline(True)
        font.setKerning(True)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.tableWidget_2 = QtWidgets.QTableWidget(self.tab_5)
        self.tableWidget_2.setGeometry(QtCore.QRect(20, 320, 571, 101))
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(1)
        self.tableWidget_2.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(0, item)
        self.pushButton_4 = QtWidgets.QPushButton(self.tab_5)
        self.pushButton_4.setGeometry(QtCore.QRect(340, 230, 111, 31))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.tab_5)
        self.pushButton_5.setGeometry(QtCore.QRect(200, 220, 111, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setObjectName("pushButton_5")
        self.tabWidget_2.addTab(self.tab_5, "")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget_3 = QtWidgets.QTabWidget(self.tab_2)
        self.tabWidget_3.setGeometry(QtCore.QRect(0, 0, 601, 461))
        self.tabWidget_3.setObjectName("tabWidget_3")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.gridLayoutWidget_4 = QtWidgets.QWidget(self.tab_6)
        self.gridLayoutWidget_4.setGeometry(QtCore.QRect(0, 10, 591, 191))
        self.gridLayoutWidget_4.setObjectName("gridLayoutWidget_4")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.gridLayoutWidget_4)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_11 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(12)
        font.setKerning(True)
        self.label_11.setFont(font)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.gridLayout_5.addWidget(self.label_11, 2, 0, 1, 1)
        self.cleanupDirectoryButton_2 = QtWidgets.QPushButton(self.gridLayoutWidget_4)
        self.cleanupDirectoryButton_2.setObjectName("cleanupDirectoryButton_2")
        self.gridLayout_5.addWidget(self.cleanupDirectoryButton_2, 0, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(12)
        font.setKerning(True)
        self.label_10.setFont(font)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.gridLayout_5.addWidget(self.label_10, 1, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(12)
        font.setKerning(True)
        self.label_9.setFont(font)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.gridLayout_5.addWidget(self.label_9, 0, 0, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(12)
        font.setKerning(True)
        self.label_12.setFont(font)
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.gridLayout_5.addWidget(self.label_12, 3, 0, 1, 1)
        self.textEdit_2 = QtWidgets.QTextEdit(self.gridLayoutWidget_4)
        self.textEdit_2.setObjectName("textEdit_2")
        self.gridLayout_5.addWidget(self.textEdit_2, 1, 1, 1, 1)
        self.textEdit_3 = QtWidgets.QTextEdit(self.gridLayoutWidget_4)
        self.textEdit_3.setObjectName("textEdit_3")
        self.gridLayout_5.addWidget(self.textEdit_3, 2, 1, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.gridLayoutWidget_4)
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.checkBox_7 = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_7.setGeometry(QtCore.QRect(60, 0, 81, 20))
        self.checkBox_7.setObjectName("checkBox_7")
        self.checkBox_8 = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_8.setGeometry(QtCore.QRect(210, 0, 81, 20))
        self.checkBox_8.setObjectName("checkBox_8")
        self.gridLayout_5.addWidget(self.groupBox_2, 3, 1, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.tab_6)
        self.label_13.setGeometry(QtCore.QRect(0, 210, 581, 41))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(13)
        font.setUnderline(True)
        font.setKerning(True)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.tab_6)
        self.label_14.setEnabled(True)
        self.label_14.setGeometry(QtCore.QRect(0, 310, 581, 41))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(13)
        font.setUnderline(False)
        font.setKerning(True)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.tab_6)
        self.label_15.setEnabled(True)
        self.label_15.setGeometry(QtCore.QRect(210, 310, 41, 41))
        self.label_15.setText("")
        self.label_15.setPixmap(QtGui.QPixmap("check.png"))
        self.label_15.setScaledContents(True)
        self.label_15.setObjectName("label_15")
        self.pushButton_6 = QtWidgets.QPushButton(self.tab_6)
        self.pushButton_6.setGeometry(QtCore.QRect(10, 250, 111, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setObjectName("pushButton_6")
        self.tabWidget_3.addTab(self.tab_6, "")
        self.tab_7 = QtWidgets.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.tabWidget_3.addTab(self.tab_7, "")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.tabWidget.addTab(self.tab_3, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 611, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        self.tabWidget_2.setCurrentIndex(1)
        self.tabWidget_3.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Office Helper"))
        self.groupBox.setTitle(_translate("MainWindow", "GroupBox"))
        self.directoryButton.setText(_translate("MainWindow", "Directory"))
        self.label_3.setText(_translate("MainWindow", "Choose the file types to search:"))
        self.label.setText(_translate("MainWindow", "Type a regex you want to search for:"))
        self.label_2.setText(_translate("MainWindow", "Choose a file or directory to search:"))
        self.fileButton.setText(_translate("MainWindow", "File"))
        self.pdfCheck.setText(_translate("MainWindow", ".pdf"))
        self.docxCheck.setText(_translate("MainWindow", ".docx"))
        self.txtCheck.setText(_translate("MainWindow", ".txt"))
        self.docCheck.setText(_translate("MainWindow", ".doc"))
        self.label_4.setText(_translate("MainWindow", "Your matches in:"))
        item = self.regexTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Text"))
        item = self.regexTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "File"))
        item = self.regexTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Line"))
        self.searchButton.setText(_translate("MainWindow", "Search"))
        self.regexExportButton.setText(_translate("MainWindow", "Export results to txt"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_4), _translate("MainWindow", "Regex Search"))
        self.label_6.setText(_translate("MainWindow", "Select extensions to delete:"))
        self.cleanupDirectoryButton.setText(_translate("MainWindow", "Directory"))
        self.label_5.setText(_translate("MainWindow", "Choose a directory to clean up:"))
        self.checkBox.setText(_translate("MainWindow", ".docx"))
        self.checkBox_3.setText(_translate("MainWindow", ".pptx"))
        self.checkBox_2.setText(_translate("MainWindow", ".png"))
        self.checkBox_4.setText(_translate("MainWindow", ".xlsx"))
        self.checkBox_5.setText(_translate("MainWindow", ".pdf"))
        self.checkBox_6.setText(_translate("MainWindow", ".jpg"))
        self.label_7.setText(_translate("MainWindow", "Other extensions to delete (separated by commas)"))
        self.label_8.setText(_translate("MainWindow", "Deleting files in:"))
        item = self.tableWidget_2.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "File"))
        self.pushButton_4.setText(_translate("MainWindow", "Export log to txt"))
        self.pushButton_5.setText(_translate("MainWindow", "Delete"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_5), _translate("MainWindow", "Cleanup"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Files"))
        self.label_11.setText(_translate("MainWindow", "Enter owner password:"))
        self.cleanupDirectoryButton_2.setText(_translate("MainWindow", "Browse"))
        self.label_10.setText(_translate("MainWindow", "Enter user password:"))
        self.label_9.setText(_translate("MainWindow", "Choose a pdf file:"))
        self.label_12.setText(_translate("MainWindow", "Encryption bits:"))
        self.checkBox_7.setText(_translate("MainWindow", "40"))
        self.checkBox_8.setText(_translate("MainWindow", "128"))
        self.label_13.setText(_translate("MainWindow", "Encrypting PDF:"))
        self.label_14.setText(_translate("MainWindow", "Encryption complete!"))
        self.pushButton_6.setText(_translate("MainWindow", "Encrypt"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_6), _translate("MainWindow", "Encryption"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_7), _translate("MainWindow", "Merging"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "PDFs"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "CSV/Excel Conversion"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
